name: 方法1随机访问
on:
  push:
    branches:
      - main
  schedule: # 如需修改运行次数，请修改此表达式，在线生成表达式：https://cron.qqe2.com/
    - cron: '0 0/20 * * * ? *' 
  workflow_dispatch:
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: 'set timestamp'
        run: |
            sudo timedatectl set-timezone 'Asia/Shanghai'
            echo `date +"%Y-%m-%d %H:%M:%S"  ` >> random_click.log
      - name: '运行'
        run: |
          node "方法1.random_click/momo_random.js"
        env:
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      
      - name: Commit #上传新的random_click.log到仓库
        run: |
            git config --global user.email 1487819688@qq.com
            git config --global user.name robot
            git add random_click.log
            git commit -m "Run Log Commit" -a
  
      - name: Push changes
        uses: ad-m/github-push-action@master
